Allow user to view a calendar week
* Install mobiscroll and jest-canvas-mock
  For calendar: https://mobiscroll.com/

  `jest-canvas-mock` is required to test mobiscroll `Datepicker`
  component. Without it, you get an error:

  ```
  Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
  ```
* Introduce CalendarWeek component w/test
* Add CalendarWeek component to App render